### PR TITLE
fix bug at getHandlerFilename if not dot in string

### PR DESCRIPTION
**Pull request by vbryan**
Linked issue: https://github.com/dougmoscrop/serverless-plugin-include-dependencies/issues/33

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Sorry, I can merge this, but please add a test.

**Comment by aychtang** [comment]
@vbryan @dougmoscrop Would you like me to pick up this issue?

**Comment by dougmoscrop** [comment]
Sure if you have the time, thanks, just some testing.

**Comment by aychtang** [comment]
Cool, we're using this package internally at my company for a new project so I'm happy to help there

**Comment by aychtang** [comment]
@vbryan Is the approach you took in this commit correct? I was reading a bit about the GCP examples and it seems you're supposed to export all functions from the index file when using this syntax without the . in the sls handler name.

**Comment by aychtang** [comment]
@dougmoscrop What do you want done on this?

I think in any case the handler file for a config given `handler: src/handler` is not `src/handle`, so I could follow this fix approach and have it return `src/handler`.

However it seems from the basic GCP examples that such handlers should be exported from the `index` file, would you like me to fix the function to return the `index` file in these cases?

That should work for this example: https://github.com/serverless/examples/tree/master/google-node-simple-http-endpoint

**Comment by dougmoscrop** [comment]
that sounds reasonable, yeah - as long as nothing backwards breaks I'm happy to have anything that could work start working

**Pull request closed without merging**
